install.packages("readxl")
install.packages("dplyr")
install.packages("openxlsx")
install.packages("moments")

install.packages("lawstat")
install.packages("BSDA")
install.packages("EnvStats")
install.packages("binom")
install.packages("car")
install.packages("dunn.test")

install.packages("lsr")
install.packages("epiR")
install.packages("nortest")
#install.packages('IRkernel')
#IRkernel::installspec(user = TRUE)
